# Site settings
title: Raya Dance Station
description: > # this means to ignore newlines until "baseurl:"
repository: vvalchev/raya-dance-site
baseurl: "/raya-dance-site/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Copyright &copy; 2024 - Raya Dance Station
lang: bg

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
  - vendor
defaults:
  - scope:
      path: "assets/images/gallery"
    values:
      gallery: true
